encoders:
  - name: One-Hot
    columns:
      - weather_category

features:
  categorical:
    - weather_category
  numerical:
    - max_temp
    - min_temp
    - avg
    - rng
    - cdd
    - hdd
    - dow_sin
    - dow_cos
    - mon_sin
    - mon_cos
  binary:
    - hot
    - cold
    - weekend
    - holiday

model:
  target: max_power
  test_size: 0.2
  random_state: 42