[project]
name = "power-forecasting-mlops"
version = "0.1.0"
description = ""
authors = [
    {name = "Ryo Watanabe",email = "ryopoaro03290024@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "polars (>=1.29.0,<2.0.0)",
    "numpy (>=2.2.5,<3.0.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "ruff (>=0.11.8,<0.12.0)",
    "holidays (>=0.72,<0.73)",
    "category-encoders (>=2.8.1,<3.0.0)",
    "omegaconf (>=2.3.0,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
