[project]
name = "power-forecasting-mlops"
version = "0.1.0"
description = ""
authors = [
    {name = "Ryo Watanabe",email = "ryopoaro03290024@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "polars (>=1.29.0,<2.0.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "ruff (>=0.11.8,<0.12.0)",
    "holidays (>=0.72,<0.73)",
    "category-encoders (>=2.8.1,<3.0.0)",
    "omegaconf (>=2.3.0,<3.0.0)",
    "lightgbm (>=4.6.0,<5.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "japanize-matplotlib (>=1.1.3,<2.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "sagemaker (>=2.244.0,<3.0.0)",
    "boto3 (>=1.38.12,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
lint.select = ["ALL"]
lint.ignore = [
    "D",
    "PLR0913",
    "ANN002",
    "ANN003",
]
target-version = "py311"

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "S101",
    "ANN201",
    "N802",
    "ARG",
]

[tool.ruff.lint.pydocstyle]
convention = "google"