run:
  region: ap-northeast-1
  role: arn:aws:iam::163817410757:role/service-role/power-forecasting-role-dev
  deployment_role: arn:aws:iam::163817410757:role/lambda-deploy-serverless-role-dev
  default_bucket: power-forecasting-mlops-dev
  pipeline_name: PowerForecastPipeline
  environment: dev
  enable_cache: True

pipeline:
  weather_data_s3: s3://power-forecasting-mlops-dev/data/weather_data.csv
  power_usage_s3: s3://power-forecasting-mlops-dev/data/power_usage/
  processing_instance_type: ml.t3.medium
  processing_instance_count: 1
  training_instance_type: ml.m5.large
  training_instance_count: 1
  mse_threshold: 999999.0