# testとtrainのデータを分ける日付（YYYY-MM-DD形式）
split_date: 2024-10-01
# エンコーダーの設定（One-HotエンコーディングとOrdinalエンコーディングに対応）
encoders:
  - name: One-Hot
    columns:
      - weather_category
# 特徴量の設定
feature_thresholds:
  hot_day: 30
  cold_day: 5
  cdd_base: 18
  hdd_base: 18
